<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreResumeRequest extends FormRequest
{
    // protected $stopOnFirstFailure = true;


    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'birth_day' => 'required|date',
            'name' => 'required|bail',
            'surname' => 'bail|required',
            'speciality' => 'required|string'
        ];
    }

    public function attributes()
    {
        // return parent::attributes(); // TODO: Change the autogenerated stub
        return [
            'surname' => 'фамилия',
            'name' => 'имя',
            'birthday' => 'дата рождения',
            'birth day' => 'дата рождения',
            'city' => 'город',
            'citizen' => 'гражданство',
            'speciality' => 'специальность',

        ];
    }

    public function messages()
    {
        // return parent::messages(); // TODO: Change the autogenerated stub
        return [
            'birthday.date_format' => 'Дата рождения должна в формате даты',
        ];
    }

}
